[build]
  command = "hugo"
  publish = "public"


[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"


[context.deploy-preview.environment]
  HUGO_VERSION = "0.37"


[context.production.environment]
  HUGO_VERSION = "0.37"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
